version: '2.2'

services:
  mysql-container:
    image: mysql:latest
    cpus: '0.25'
    mem_limit: 250M
    restart: always
    networks:
      - test-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=poledb
      - MYSQL_USER=daniel
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  concrete-test-container:
    image: concrete-test-app:latest
    cpus: '0.30'
    mem_limit: 300M
    networks:
      - test-network
    ports:
      - "8086:8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://mysql-container/poledb?serverTimezone=Europe/Budapest
      - DATASOURCE_USERNAME=daniel
      - DATASOURCE_PASSWORD=123456
      - HOST=smtp.gmail.com
      - PORT=587
      - MAIL_USERNAME=polestudioconcrete@gmail.com
      - MAIL_PASSWORD=concretepole2020
      - APPLICATION_URL=http://18.156.155.60:8086
      - JWT_SECRET_KEY=Secret_Key
      - JWT_EXPIRATION=840000000
      - JAVA_OPTS=-Xmx300M -Xms200M -XX:MaxRAM=300M
    depends_on:
      - mysql-container

volumes:
  mysql_data:

networks:
  test-network:
